name: Build SDK Package
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Build SDK
        run: |
          yarn
          export BRANCH_NAME=${GITHUB_REF#refs/heads/}
          export BUILD_JOB_ID=$GITHUB_RUN_ID
          yarn build
          mkdir sdk_package
          cp package.json sdk_package/package.json
          cp -r dist sdk_package/dist

      - uses: actions/upload-artifact@v4
        with:
          name: sdk_package
          path: sdk_package